import type { Metadata } from "next";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

import "./globals.css";


export const metadata: Metadata = {
  title: "기업",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>        
        <p id="accessibility"><a href="#container">본문바로가기</a></p>
        <div id="wrap">
            <Header />
            <div id="container">
                {children}
            </div>
            <Footer />
        </div>
      </body>
    </html>
  );
}
